#pragma once

#define	VERSION							"Frecurse v1.2.0"

#define MAX_DELAY_TIME					2.0f

#define BG_RED							0.58f
#define BG_GREEN						0.18f
#define BG_BLUE							0.24f
#define BG_ALPHA						1.0f

#define PI								3.14159

#define HEIGHT							400
#define WIDTH							400

#define SLIDER_WIDTH					100
#define SLIDER_HEIGHT					100

#define LIN_SLIDER_WIDTH				70
#define LIN_SLIDER_HEIGHT				24

#define SLIDER_LABEL_WIDTH				100
#define SLIDER_LABEL_HEIGHT				24

#define TEXTBOX_WIDTH					40
#define TEXTBOX_HEIGHT					20

#define GLOBAL_X						50
#define GLOBAL_Y						50

#define FB_GAIN_SLIDER_X				0
#define FB_GAIN_SLIDER_Y				15
#define FB_GAIN_LABEL_X					0
#define FB_GAIN_LABEL_Y					-10

#define DELAYMS_SLIDER_X				100
#define DELAYMS_SLIDER_Y				15
#define DELAYMS_LABEL_X					100
#define DELAYMS_LABEL_Y					-10

#define DELAYBPM_SLIDER_X				DELAYMS_SLIDER_X
#define DELAYBPM_SLIDER_Y				DELAYMS_SLIDER_Y
#define DELAYBPM_LABEL_X				DELAYMS_LABEL_X
#define DELAYBPM_LABEL_Y				DELAYMS_LABEL_Y

#define FB_GAIN_SLIDER_X2				0
#define FB_GAIN_SLIDER_Y2				165
#define FB_GAIN_LABEL_X2				0
#define FB_GAIN_LABEL_Y2				140

#define DELAYMS_SLIDER_X2				100
#define DELAYMS_SLIDER_Y2				165
#define DELAYMS_LABEL_X2				100
#define DELAYMS_LABEL_Y2				140

#define DELAYBPM_SLIDER_X2				DELAYMS_SLIDER_X2
#define DELAYBPM_SLIDER_Y2				DELAYMS_SLIDER_Y2
#define DELAYBPM_LABEL_X2				DELAYMS_LABEL_X2
#define DELAYBPM_LABEL_Y2				DELAYMS_LABEL_Y2

#define MIX_SLIDER_X					200
#define MIX_SLIDER_Y					15
#define MIX_LABEL_X						200
#define MIX_LABEL_Y						-10

#define LFOFREQ_SLIDER_X				200
#define LFOFREQ_SLIDER_Y				165
#define LFOFREQ_LABEL_X					200
#define LFOFREQ_LABEL_Y					140

#define LFOENA_BUT_X					237
#define LFOENA_BUT_Y					290
#define LFOENA_BUT_WIDTH				40
#define LFOENA_BUT_HEIGHT				40
#define LFOENA_LABEL_X					257
#define LFOENA_LABEL_Y					305
#define LFOENA_BUT_LAB_HEIGHT			10
#define LFOENA_BUT_LAB_WIDTH			30

#define LFOAMT_SLIDER_X					215
#define LFOAMT_SLIDER_Y					265
#define LFOAMT_LABEL_X					195
#define LFOAMT_LABEL_Y					271
#define LFOAMT_LAB_HEIGHT				10
#define LFOAMT_LAB_WIDTH				30

#define TESTRVRB_BUT_X					-50
#define TESTRVRB_BUT_Y					437
#define TESTRVRB_BUT_WIDTH				40
#define TESTRVRB_BUT_HEIGHT				40
#define TESTRVRB_LABEL_X				-30
#define TESTRVRB_LABEL_Y				452
#define TESTRVRB_BUT_LAB_HEIGHT			10
#define TESTRVRB_BUT_LAB_WIDTH			100

#define STRODEL_BUT_X					90
#define STRODEL_BUT_Y					290
#define STRODEL_BUT_WIDTH				40
#define STRODEL_BUT_HEIGHT				40
#define STRODEL_LABEL_X					110
#define STRODEL_LABEL_Y					305
#define STRODEL_BUT_LAB_HEIGHT			10
#define STRODEL_BUT_LAB_WIDTH			100

#define BPMSYNC_BUT_X					-50
#define BPMSYNC_BUT_Y					45
#define BPMSYNC_BUT_WIDTH				40
#define BPMSYNC_BUT_HEIGHT				40
#define BPMSYNC_LABEL_X					-30
#define BPMSYNC_LABEL_Y					60
#define BPMSYNC_BUT_LAB_HEIGHT			10
#define BPMSYNC_BUT_LAB_WIDTH			100

#define BPMSYNC2_BUT_X					-50
#define BPMSYNC2_BUT_Y					195
#define BPMSYNC2_BUT_WIDTH				40
#define BPMSYNC2_BUT_HEIGHT				40
#define BPMSYNC2_LABEL_X				-30
#define BPMSYNC2_LABEL_Y				210
#define BPMSYNC2_BUT_LAB_HEIGHT			10
#define BPMSYNC2_BUT_LAB_WIDTH			100

#define DELAYMSLEFT_VALDISP_LABEL_X		100
#define DELAYMSLEFT_VALDISP_LABEL_Y		55

#define DELAYMSRIGHT_VALDISP_LABEL_X	100
#define DELAYMSRIGHT_VALDISP_LABEL_Y	205

#define DELAYBPMLEFT_VALDISP_LABEL_X	100
#define DELAYBPMLEFT_VALDISP_LABEL_Y	55

#define DELAYBPMRIGHT_VALDISP_LABEL_X	100
#define DELAYBPMRIGHT_VALDISP_LABEL_Y	205

#define GAINLEFT_VALDISP_LABEL_X		0
#define GAINLEFT_VALDISP_LABEL_Y		55

#define GAINRIGHT_VALDISP_LABEL_X		0
#define GAINRIGHT_VALDISP_LABEL_Y		205

#define DRYWET_VALDISP_LABEL_X			200
#define DRYWET_VALDISP_LABEL_Y			55

#define LFOFREQ_VALDISP_LABEL_X			200
#define LFOFREQ_VALDISP_LABEL_Y			205

#define VALUE_LABEL_HEIGHT				15
#define VALUE_LABEL_WIDTH				100