name: Windows Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.gitignore'
    - 'testalg/**'
    - 'LICENSE'
    - 'README.md'
    - 'TestDelay.filtergraph'
    - 'TestingHostApp.exe'
    - 'getBuild'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '.gitignore'
    - 'testalg/**'
    - 'LICENSE'
    - 'README.md'
    - 'TestDelay.filtergraph'
    - 'TestingHostApp.exe'
    - 'getBuild'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:      
      matrix:           
        plugin: ["Delay", "Reverb"] 
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPLUGIN=${{matrix.plugin}} -DACTIONS=TRUE

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


